### ISSUE TITLE
Starting and stopping the OpenCV stream sometimes gives a segmentation fault: 11

### ISSUE THREAD

**Issue by maansaake** [semgroup4/MARSEMControlApplication#21]
When starting and stopping the OpenCV stream, we sometimes get a segmentation fault: 11 error that crashes the program without a stack trace to look at. Look into error handling of the opencv.py file.

**Comment by maansaake** [comment]
Seems like it happens more often when the stream is stopped that started.

**Comment by snogaraleal** [comment]
A segmentation fault comes from a memory management operation such as
writing to a memory address that is not reserved, or not enough memory in
the system. To see where it comes from it's possible to run the executable
with Valgrind http://valgrind.org/, although we probably cannot fix a
segmentation fault.

**Comment by crkt** [comment]
The problem was you're not allowed to edit UI Elements in Kivy in anything but the main thread.

Closing this issue.

**Comment by maansaake** [comment]
Going to try and schedule updates using the Kivy Clock instead of a while loop. This is to prevent locking the main thread and being able to manipulate images in the main thread instead. All of this crap to prevent segmentation faults...

**Comment by crkt** [comment]
Sounds good. Give us an update on slack when you're done.

May the source be with you.

**Comment by maansaake** [comment]
This is solved! We're running openCV in its native window, so no kivy image object needs to be fucked with any more.
